# docker-compose.yml

services:
  app:
    build: .
    ports:
      - "3000:3000"
      # Port 9229 für den Node.js Debugger freigeben
      - "9229:9229"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules